In [4]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np
arr=np.array(range(6))
print(arr.dtype)

int64


In [5]:
#2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
is_float=arr.dtype==np.float64
print(is_float)

True


In [6]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr=np.array([1+5j,2+2j,6+3j],dtype=np.complex128)
print(arr)

[1.+5.j 2.+2.j 6.+3.j]


In [7]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr=np.array([1,23,4,53,2])
arr_tofloat=arr.astype(np.float64)
print(arr_tofloat)

[ 1. 23.  4. 53.  2.]


In [8]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision
arr=np.array(range(6),dtype=np.float64)
arr_converted=arr.astype(np.float32)
print(arr_converted)

[0. 1. 2. 3. 4. 5.]


In [9]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
#type.
def array_attributes(arr):
    shape=arr.shape
    size=arr.size
    data_type=arr.dtype
    return shape,size,data_type

#example usage
arr=np.array([[2,3,5],[2,5,8]],dtype=np.int64)
shape, size, dtype = array_attributes(arr)
print(f"Shape: {shape}, Size: {size}, Data Type: {dtype}")

    



Shape: (2, 3), Size: 6, Data Type: int64


In [10]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
    dimension=arr.ndim
    return dimension
#example usage
arr=np.array([[2,4,5],[5,78,3]],dtype=np.int64)
dimension=array_dimension(arr)
print(f"Dimension:{dimension}")

Dimension:2


In [11]:
 #8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
#size in bytes.
def item_size_info(arr):
     item_size = arr.itemsize
     total_size = arr.nbytes
     return item_size, total_size

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
item_size, total_size = item_size_info(arr)
print(f"Item Size: {item_size} bytes, Total Size: {total_size} bytes")
    

Item Size: 4 bytes, Total Size: 24 bytes


In [12]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
strides = array_strides(arr)
print(f"Strides: {strides}")

Strides: (12, 4)


In [13]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
#and strides of the array.
def shape_stride_relationship(arr):
    shape=arr.shape
    strides_ofarray=arr.strides
    return shape,strides_ofarray
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
shape, strides = shape_stride_relationship(arr)
print(f"Shape: {shape}, Strides: {strides}")

Shape: (2, 3), Strides: (12, 4)


In [14]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
#zeros with `n` elements.
def create_zeros_array(n):
    return np.zeros(n)

# Example usage:
n = 5
zeros_array = create_zeros_array(n)
print(zeros_array)
    


[0. 0. 0. 0. 0.]


In [15]:
#12. Write a function `create_ones_matrix` that takces integers `rows` and `cols` as inputs and generates a 2D
#NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix(rows,cols):
    return np.ones((rows, cols))

# Example usage:
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)
    

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
#`step`.
def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)

#example usage
start=0
stop=10
step=2 
arr=generate_range_array(start,stop,step)
print(arr)

[0 2 4 6 8]


In [17]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
#(inclusive).
def generate_linear_space(start,stop,num):
      return np.linspace(start, stop, num)

# Example usage:
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print(linear_space_array)
    

[0.   0.25 0.5  0.75 1.  ]


In [18]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
#identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
     return np.eye(n)

# Example usage:
n = 4
identity_matrix = create_identity_matrix(n)
print(identity_matrix)
    
    

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
#16. Write a function that takes a Python list and converts it into a NumPy array.
def list_to_numpy_array(py_list):
    return np.array(py_list)

# Example usage:
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(py_list)
print(numpy_array)
print(type(numpy_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
#same data.
original_array = np.array([1, 2, 3, 4, 5])

# Create a view of the original array
view_array = original_array.view()

# Modify the view array
view_array[0] = 99

# Print both arrays to see the effect
print("Original array:", original_array)
print("View array:", view_array)

Original array: [99  2  3  4  5]
View array: [99  2  3  4  5]


In [21]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis
def concatenate_arrays(arr1,arr2,axis=0):
     return np.concatenate((arr1, arr2), axis=axis)

# Example usage:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate along axis 0 (rows)
concatenated_array_axis0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:\n", concatenated_array_axis0)

# Concatenate along axis 1 (columns)
concatenated_array_axis1 = concatenate_arrays(arr1, arr2, axis=1)
print("Concatenated along axis 1:\n", concatenated_array_axis1)

Concatenated along axis 0:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenated along axis 1:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [22]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
#concatenate`.
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])

# Concatenate the arrays horizontally (along axis 1)
concatenated_array = np.concatenate((arr1, arr2), axis=1)

print("Concatenated horizontally:\n", concatenated_array)

Concatenated horizontally:
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [23]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertically_stack_arrays(array_list):
    
    return np.vstack(array_list)

# Example usage:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])
arr3 = np.array([[7, 8, 9]])

array_list = [arr1, arr2, arr3]
stacked_array = vertically_stack_arrays(array_list)
print("Vertically stacked array:\n", stacked_array)

Vertically stacked array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
import numpy as np

def create_array_in_range(start, end, step):
    return np.arange(start, end + 1, step)

# Example usage:
array1 = create_array_in_range(1, 10, 2)
print(array1)


[1 3 5 7 9]


In [25]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

import numpy as np

def generate_equally_spaced_values():
    return np.linspace(0, 1, 10)

# Example usage:
array2 = generate_equally_spaced_values()
print(array2)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [26]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

import numpy as np

def create_log_spaced_values():
    return np.logspace(0, 3, 5)

# Example usage:
array3 = create_log_spaced_values()
print(array3)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [27]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

import numpy as np
import pandas as pd

def create_random_dataframe():
    data = np.random.randint(1, 101, size=(5, 3))
    return pd.DataFrame(data, columns=['A', 'B', 'C'])

# Example usage:
df = create_random_dataframe()
print(df)


    A   B   C
0  15  35  91
1  46  74  28
2  68  57  98
3  59  81  50
4  52  50  31


In [28]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

import numpy as np
import pandas as pd

def replace_negatives_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage:
df = pd.DataFrame({'A': [1, -2, 3, -4, 5], 'B': [5, -6, 7, 8, -9]})
print("Before:")
print(df)
df = replace_negatives_with_zero(df, 'A')
print("After:")
print(df)


Before:
   A  B
0  1  5
1 -2 -6
2  3  7
3 -4  8
4  5 -9
After:
   A  B
0  1  5
1  0 -6
2  3  7
3  0  8
4  5 -9


In [29]:
#26. Access the 3rd element from the given NumPy array: arr = np.array([10, 20, 30, 40, 50])

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Accessing the 3rd element (index 2 since indexing starts from 0)
third_element = arr[2]
print(third_element)


30


In [30]:
#.27. Retrieve the element at index (1, 2) from the 2D NumPy array: arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Retrieving the element at index (1, 2)
element = arr_2d[1, 2]
print(element)


6


In [31]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array: arr = np.array([3, 8, 2, 10, 5, 7])

import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

# Extracting elements greater than 5
filtered_elements = arr[arr > 5]
print(filtered_elements)


[ 8 10  7]


In [32]:
#29.Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array: arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]). Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extracting elements from index 2 to 5 (inclusive)
sliced_elements = arr[2:6]
print(sliced_elements)


[3 4 5 6]


In [33]:
#30.Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array
  #arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Extracting the sub-array
sub_array = arr_2d[0:2, 1:3]

print("Original array:")
print(arr_2d)
print("Sub-array:")
print(sub_array)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub-array:
[[2 3]
 [5 6]]


In [34]:
#31. Write a NumPy function to extract elements in a specific order from a given 2D array based on indices provided in another array.

import numpy as np

def extract_elements(arr, indices):
    return arr[indices[:, 0], indices[:, 1]]

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [1, 2], [2, 0]])
result = extract_elements(arr, indices)
print(result)


[2 6 7]


In [35]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

import numpy as np

def filter_elements(arr, threshold):
    return arr[arr > threshold]

# Example usage:
arr = np.array([1, 5, 8, 12, 3])
result = filter_elements(arr, 5)
print(result)


[ 8 12]


In [36]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

import numpy as np

def extract_elements_3d(arr, x_indices, y_indices, z_indices):
    return arr[x_indices, y_indices, z_indices]

# Example usage:
arr = np.random.randint(1, 10, size=(3, 3, 3))
x_indices = np.array([0, 1, 2])
y_indices = np.array([1, 2, 0])
z_indices = np.array([2, 0, 1])
result = extract_elements_3d(arr, x_indices, y_indices, z_indices)
print(result)


[4 5 2]


In [37]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

import numpy as np

def elements_satisfying_conditions(arr, condition1, condition2):
    return arr[(arr > condition1) & (arr < condition2)]

# Example usage:
arr = np.array([1, 5, 8, 12, 3])
result = elements_satisfying_conditions(arr, 4, 10)
print(result)


[5 8]


In [38]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

import numpy as np

def extract_elements_by_indices(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
result = extract_elements_by_indices(arr, row_indices, col_indices)
print(result)


[2 6 7]


In [39]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting

import numpy as np

def add_scalar(arr, scalar):
    return arr + scalar

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = add_scalar(arr, 5)
print(result)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [40]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting

import numpy as np

def multiply_rows(arr1, arr2):
    return arr1.T * arr2

# Example usage:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
result = multiply_rows(arr1, arr2)
print(result)


[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


In [41]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

import numpy as np

def add_to_each_row(arr1, arr2):
    return arr1 + arr2

# Example usage:
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13], [14, 15, 16]])
result = add_to_each_row(arr1.T, arr2)
print(result)


[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [42]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

import numpy as np

def add_arrays(arr1, arr2):
    return arr1 + arr2

# Example usage:
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
result = add_arrays(arr1, arr2)
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [43]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

import numpy as np

def multiply_with_broadcasting(arr1, arr2):
    arr1_expanded = np.expand_dims(arr1, axis=2)
    arr2_expanded = np.expand_dims(arr2, axis=0)
    return arr1_expanded * arr2_expanded

# Example usage:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])
result = multiply_with_broadcasting(arr1, arr2)
print(result)


ValueError: operands could not be broadcast together with shapes (2,3,1) (1,2,2) 

In [44]:
#41. Calculate column-wise mean for the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

def column_wise_mean(arr):
    return np.mean(arr, axis=0)

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = column_wise_mean(arr)
print(result)


[2.5 3.5 4.5]


In [45]:
#42. Find maximum value in each row of the given array:
   
   #arr = np.array([[1, 2, 3], [4, 5, 6]])
   
import numpy as np

def max_in_each_row(arr):
    return np.max(arr, axis=1)

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = max_in_each_row(arr)
print(result)


[3 6]


In [46]:
#43. For the given array, find indices of maximum value in each column:
 
  # arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

def indices_of_max_in_each_column(arr):
    return np.argmax(arr, axis=0)

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = indices_of_max_in_each_column(arr)
print(result)


[1 1 1]


In [47]:
#44. For the given array, apply custom function to calculate moving sum along rows:
   
 #  arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

def moving_sum(arr):
    def row_moving_sum(row):
        return np.cumsum(row)
    
    return np.apply_along_axis(row_moving_sum, 1, arr)

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = moving_sum(arr)
print(result)


[[ 1  3  6]
 [ 4  9 15]]


In [48]:
#45. In the given array, check if all elements in each column are even:
   
   #arr = np.array([[2, 4, 6], [3, 5, 7]])

import numpy as np

def all_even_in_each_column(arr):
    return np.all(arr % 2 == 0, axis=0)

# Example usage:
arr = np.array([[2, 4, 6], [3, 5, 7]])
result = all_even_in_each_column(arr)
print(result)


[False False False]


In [49]:
#46. Given a NumPy array and m, n, reshape it into a matrix of dimensions m rows and n columns. Return reshaped matrix:
   
   #original_array = np.array([1, 2, 3, 4, 5, 6])

import numpy as np

def reshape_array(original_array, m, n):
    return np.reshape(original_array, (m, n))

# Example usage:
original_array = np.array([1, 2, 3, 4, 5, 6])
result = reshape_array(original_array, 2, 3)
print(result)


[[1 2 3]
 [4 5 6]]


In [50]:
#47. Create a function that takes a matrix as input and returns the flattened array:
 
 #  input_matrix = np.array([[1, 2, 3], [4, 5, 6]])


import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()

# Example usage:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
result = flatten_matrix(input_matrix)
print(result)


[1 2 3 4 5 6]


In [51]:
#48. Write a function that concatenates two given arrays along a specified axis:
   #array1 = np.array([[1, 2], [3, 4]])
   #array2 = np.array([[5, 6], [7, 8]])

import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

# Example usage:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
result_axis0 = concatenate_arrays(array1, array2, axis=0)
result_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 0:")
print(result_axis0)
print("Concatenated along axis 1:")
print(result_axis1)


Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [52]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.

   # original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    

import numpy as np

def split_array(array, num_splits, axis=0):
    return np.array_split(array, num_splits, axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = split_array(original_array, 3, axis=0)
print(result)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [53]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
    
    #original_array = np.array([1, 2, 3, 4, 5])
    #indices_to_insert = [2, 4]
    #values_to_insert = [10, 11]
    #indices_to_delete = [1, 3]
    
import numpy as np

def insert_and_delete_elements(array, insert_indices, insert_values, delete_indices):
    array = np.insert(array, insert_indices, insert_values)
    array = np.delete(array, delete_indices)
    return array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result)
   

[ 1 10  4 11  5]


In [54]:
#51. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 10. Perform element-wise addition between arr1 and arr2.

import numpy as np

arr1 = np.random.randint(1, 100, size=10)
arr2 = np.arange(1, 11)
result = arr1 + arr2
print(result)


[39 13 78 14  7 99 36 85 70 89]


In [55]:
#52. Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise.

import numpy as np

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2
print(result)


[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [56]:
#53. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2.

import numpy as np

arr1 = np.random.randint(1, 100, size=5)
arr2 = np.arange(1, 6)
result = arr1 * arr2
print(result)


[ 84 196 111  40  50]


In [57]:
#54. Generate a NumPy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1 to 5. Perform element-wise division of arr1 by arr2.

import numpy as np

arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result = arr1 / arr2
print(result)


[2. 2. 2. 2. 2.]


In [58]:
#55. Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise.

import numpy as np

arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
result = arr1 ** arr2
print(result)


[ 1 16 27 16  5]


In [60]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

   # arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

import numpy as np

def count_substring_occurrences(arr, substring):
    return np.char.count(arr, substring).sum()

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
result = count_substring_occurrences(arr, substring)
print(result)
   

3


In [61]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.
    
   # arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
 
import numpy as np

def extract_uppercase(arr):
    return np.array([''.join([char for char in string if char.isupper()]) for string in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result = extract_uppercase(arr)
print(result)
    

['H' 'W' 'OAI' 'GPT']


In [62]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
    
   # arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
    
import numpy as np

def replace_substring(arr, old_substr, new_substr):
    return np.char.replace(arr, old_substr, new_substr)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substr = 'apple'
new_substr = 'fruit'
result = replace_substring(arr, old_substr, new_substr)
print(result)


['fruit' 'banana' 'grape' 'pinefruit']


In [63]:
#59. Write a function that concatenates strings in a NumPy array element-wise.
    
   # arr1 = np.array(['Hello', 'World'])
     #arr2 = np.array(['Open', 'AI'])
    
import numpy as np

def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result = concatenate_strings(arr1, arr2)
print(result)
   

['HelloOpen' 'WorldAI']


In [64]:
#60. Write a function that finds the length of the longest string in a NumPy array.
    
   # arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
import numpy as np

def longest_string_length(arr):
    return max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = longest_string_length(arr)
print(result)
    

9


In [65]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

import numpy as np

data = np.random.randint(1, 1001, size=100)
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_deviation = np.std(data)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_deviation}")


Mean: 484.68
Median: 503.0
Variance: 77647.3376
Standard Deviation: 278.65271863019746


In [66]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

import numpy as np

data = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")


25th Percentile: 23.25
75th Percentile: 64.75


In [67]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.

import numpy as np

arr1 = np.random.randint(1, 101, size=50)
arr2 = np.random.randint(1, 101, size=50)
correlation_coefficient = np.corrcoef(arr1, arr2)

print("Correlation Coefficient Matrix:")
print(correlation_coefficient)


Correlation Coefficient Matrix:
[[ 1.         -0.08783289]
 [-0.08783289  1.        ]]


In [68]:
#64. Create two matrices and perform matrix multiplication using NumPy's dot function.

import numpy as np

matrix1 = np.random.randint(1, 10, size=(3, 3))
matrix2 = np.random.randint(1, 10, size=(3, 3))
result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)
print("Matrix Multiplication Result:")
print(result)


Matrix 1:
[[4 8 8]
 [2 4 2]
 [7 6 3]]
Matrix 2:
[[4 3 5]
 [5 8 9]
 [8 7 5]]
Matrix Multiplication Result:
[[120 132 132]
 [ 44  52  56]
 [ 82  90 104]]


In [69]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

import numpy as np

data = np.random.randint(10, 1001, size=50)
percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)
percentile_90 = np.percentile(data, 90)
first_quartile = np.percentile(data, 25)
third_quartile = np.percentile(data, 75)

print(f"10th Percentile: {percentile_10}")
print(f"50th Percentile (Median): {percentile_50}")
print(f"90th Percentile: {percentile_90}")
print(f"First Quartile: {first_quartile}")
print(f"Third Quartile: {third_quartile}")


10th Percentile: 101.2
50th Percentile (Median): 513.0
90th Percentile: 919.3
First Quartile: 335.0
Third Quartile: 774.75


In [70]:
#66. Create a NumPy array of integers and find the index of a specific element.

import numpy as np

arr = np.array([1, 3, 5, 7, 9, 11])
element_to_find = 7
index = np.where(arr == element_to_find)[0][0]

print(f"Index of element {element_to_find}: {index}")


Index of element 7: 3


In [71]:
#67. Generate a random NumPy array and sort it in ascending order.

import numpy as np

arr = np.random.randint(1, 101, size=10)
sorted_arr = np.sort(arr)

print("Original Array:")
print(arr)
print("Sorted Array:")
print(sorted_arr)


Original Array:
[25 77  9 83 36 47 39 94 90 63]
Sorted Array:
[ 9 25 36 39 47 63 77 83 90 94]


In [72]:
#68. Filter elements >20 in the given NumPy array.

   # arr = np.array([12, 25, 6, 42, 8, 30])

import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])
filtered_arr = arr[arr > 20]

print("Filtered Array (elements > 20):")
print(filtered_arr)


Filtered Array (elements > 20):
[25 42 30]


In [73]:
#69. Filter elements which are divisible by 3 from a given NumPy array.
    
    #arr = np.array([1, 3, 5, 8, 12, 15])
    
import numpy as np

def filter_divisible_by_3(arr):
    return arr[arr % 3 == 0]

arr = np.array([1, 3, 5, 8, 12, 15])
result = filter_divisible_by_3(arr)
print(result)
    

[ 3 12 15]


In [74]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
    
    #arr = np.array([10, 20, 30, 40, 50])
 
import numpy as np

def filter_range(arr):
    return arr[(arr >= 20) & (arr <= 40)]

arr = np.array([10, 20, 30, 40, 50])
result = filter_range(arr)
print(result)


[20 30 40]


In [75]:
#71. For the given NumPy array, check its byte order using the dtype attribute byteorder.
    
    #arr = np.array([1, 2, 3])
    
import numpy as np

def check_byte_order(arr):
    return arr.dtype.byteorder

arr = np.array([1, 2, 3])
byte_order = check_byte_order(arr)
print(f"Byte order: {byte_order}")
    

Byte order: =


In [76]:
#72. For the given NumPy array, perform byte swapping in place using byteswap().
    
    #arr = np.array([1, 2, 3], dtype=np.int32)
    
import numpy as np

def byte_swap_in_place(arr):
    arr.byteswap(True)
    return arr

arr = np.array([1, 2, 3], dtype=np.int32)
result = byte_swap_in_place(arr)
print(result)
    

[16777216 33554432 50331648]


In [77]:
#73. For the given NumPy array, swap its byte order without modifying the original array using newbyteorder().

    #arr = np.array([1, 2, 3], dtype=np.int32)
    
import numpy as np

def swap_byte_order(arr):
    return arr.newbyteorder()

arr = np.array([1, 2, 3], dtype=np.int32)
result = swap_byte_order(arr)
print(result)
print("Original array:")
print(arr)
    

[16777216 33554432 50331648]
Original array:
[1 2 3]


In [78]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using newbyteorder().
    
    #arr = np.array([1, 2, 3], dtype=np.int32)
    
import numpy as np

def conditional_swap_byte_order(arr):
    if arr.dtype.byteorder == '=':
        return arr.newbyteorder()
    return arr

arr = np.array([1, 2, 3], dtype=np.int32)
result = conditional_swap_byte_order(arr)
print(result)


[16777216 33554432 50331648]


In [79]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using dtype attribute byteorder.
    
    #arr = np.array([1, 2, 3], dtype=np.int32)
 
import numpy as np

def is_byte_swapping_necessary(arr):
    return arr.dtype.byteorder == '='

arr = np.array([1, 2, 3], dtype=np.int32)
byte_swapping_necessary = is_byte_swapping_necessary(arr)
print(f"Byte swapping necessary: {byte_swapping_necessary}")


Byte swapping necessary: True


In [80]:
#76. Create a NumPy array arr1 with values from 1 to 10. Create a copy of arr1 named copy_arr and modify an element in copy_arr. Check if modifying copy_arr affects arr1.

import numpy as np

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100

print("arr1:")
print(arr1)
print("copy_arr:")
print(copy_arr)


arr1:
[ 1  2  3  4  5  6  7  8  9 10]
copy_arr:
[100   2   3   4   5   6   7   8   9  10]


In [81]:
#77. Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract a slice view_slice from the matrix. Modify an element in view_slice and observe if it changes the original matrix.

import numpy as np

matrix = np.random.randint(1, 100, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 999

print("matrix:")
print(matrix)
print("view_slice:")
print(view_slice)


matrix:
[[999  32  68]
 [  2  29  36]
 [ 39  48  75]]
view_slice:
[[999  32]
 [  2  29]]


In [82]:
#78. Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12. Extract a slice view_b from array_a and broadcast the addition of 5 to view_b. Check if it alters the original array_a.

import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :2]
view_b += 5

print("array_a:")
print(array_a)
print("view_b:")
print(view_b)


array_a:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]
view_b:
[[ 6  7]
 [ 9 10]]


In [83]:
#79. Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view of shape (4, 2) from orig_array. Modify an element in reshaped_view and check if it reflects changes in the original orig_array.

import numpy as np

orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 999

print("orig_array:")
print(orig_array)
print("reshaped_view:")
print(reshaped_view)


orig_array:
[[999   2   3   4]
 [  5   6   7   8]]
reshaped_view:
[[999   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [84]:
#80. Create a NumPy array data of shape (3, 4) with random integers. Extract a copy data_copy of elements greater than 5. Modify an element in data_copy and verify if it affects the original data.

import numpy as np

data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 999

print("data:")
print(data)
print("data_copy:")
print(data_copy)


data:
[[5 2 2 4]
 [5 2 8 7]
 [4 6 8 8]]
data_copy:
[999   7   6   8   8]


In [85]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

import numpy as np

A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

addition_result = A + B
subtraction_result = A - B

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Addition Result:")
print(addition_result)
print("Subtraction Result:")
print(subtraction_result)


Matrix A:
[[3 8 3]
 [4 5 5]
 [5 9 3]]
Matrix B:
[[4 8 1]
 [2 2 3]
 [5 8 9]]
Addition Result:
[[ 7 16  4]
 [ 6  7  8]
 [10 17 12]]
Subtraction Result:
[[-1  0  2]
 [ 2  3  2]
 [ 0  1 -6]]


In [86]:
#82. Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication.

import numpy as np

C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))

multiplication_result = np.dot(C, D)

print("Matrix C:")
print(C)
print("Matrix D:")
print(D)
print("Matrix Multiplication Result:")
print(multiplication_result)


Matrix C:
[[9 7]
 [7 7]
 [8 2]]
Matrix D:
[[4 7 4 2]
 [4 5 7 1]]
Matrix Multiplication Result:
[[64 98 85 25]
 [56 84 77 21]
 [40 66 46 18]]


In [87]:
#83. Create a matrix E and find its transpose.

import numpy as np

E = np.random.randint(1, 10, size=(3, 4))
transpose_E = E.T

print("Matrix E:")
print(E)
print("Transpose of E:")
print(transpose_E)


Matrix E:
[[4 6 7 5]
 [9 7 3 6]
 [2 3 8 4]]
Transpose of E:
[[4 9 2]
 [6 7 3]
 [7 3 8]
 [5 6 4]]


In [88]:
#84. Generate a square matrix F and compute its determinant.

import numpy as np

F = np.random.randint(1, 10, size=(3, 3))
determinant_F = np.linalg.det(F)

print("Matrix F:")
print(F)
print("Determinant of F:")
print(determinant_F)


Matrix F:
[[1 4 2]
 [9 9 5]
 [6 4 4]]
Determinant of F:
-44.000000000000014


In [89]:
#85. Create a square matrix G and find its inverse.

import numpy as np

G = np.random.randint(1, 10, size=(3, 3))
inverse_G = np.linalg.inv(G)

print("Matrix G:")
print(G)
print("Inverse of G:")
print(inverse_G)


Matrix G:
[[1 9 4]
 [6 1 4]
 [4 1 4]]
Inverse of G:
[[-4.62592927e-18  5.00000000e-01 -5.00000000e-01]
 [ 1.25000000e-01  1.87500000e-01 -3.12500000e-01]
 [-3.12500000e-02 -5.46875000e-01  8.28125000e-01]]
